/**
 * This class is generated by jOOQ
 */
package ch.johannes.example.data.schema.tables.records;


import ch.johannes.example.data.schema.tables.EntityAccessView;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityAccessViewRecord extends TableRecordImpl<EntityAccessViewRecord> implements Record3<UUID, UUID, Integer> {

	private static final long serialVersionUID = 896113035;

	/**
	 * Setter for <code>public.entity_access_view.entity_guid</code>.
	 */
	public EntityAccessViewRecord setEntityGuid(UUID value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.entity_access_view.entity_guid</code>.
	 */
	public UUID getEntityGuid() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.entity_access_view.accessor_guid</code>.
	 */
	public EntityAccessViewRecord setAccessorGuid(UUID value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.entity_access_view.accessor_guid</code>.
	 */
	public UUID getAccessorGuid() {
		return (UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.entity_access_view.access_level</code>.
	 */
	public EntityAccessViewRecord setAccessLevel(Integer value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.entity_access_view.access_level</code>.
	 */
	public Integer getAccessLevel() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<UUID, UUID, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<UUID, UUID, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return EntityAccessView.ENTITY_ACCESS_VIEW.ENTITY_GUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field2() {
		return EntityAccessView.ENTITY_ACCESS_VIEW.ACCESSOR_GUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return EntityAccessView.ENTITY_ACCESS_VIEW.ACCESS_LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getEntityGuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value2() {
		return getAccessorGuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getAccessLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntityAccessViewRecord value1(UUID value) {
		setEntityGuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntityAccessViewRecord value2(UUID value) {
		setAccessorGuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntityAccessViewRecord value3(Integer value) {
		setAccessLevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntityAccessViewRecord values(UUID value1, UUID value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EntityAccessViewRecord
	 */
	public EntityAccessViewRecord() {
		super(EntityAccessView.ENTITY_ACCESS_VIEW);
	}

	/**
	 * Create a detached, initialised EntityAccessViewRecord
	 */
	public EntityAccessViewRecord(UUID entityGuid, UUID accessorGuid, Integer accessLevel) {
		super(EntityAccessView.ENTITY_ACCESS_VIEW);

		setValue(0, entityGuid);
		setValue(1, accessorGuid);
		setValue(2, accessLevel);
	}
}
