/**
 * This class is generated by jOOQ
 */
package ch.johannes.example.data.schema.tables.records;


import ch.johannes.example.data.schema.tables.EntityAccess;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityAccessRecord extends TableRecordImpl<EntityAccessRecord> implements Record3<UUID, UUID, Integer> {

	private static final long serialVersionUID = -1611905798;

	/**
	 * Setter for <code>public.entity_access.entity_guid</code>.
	 */
	public EntityAccessRecord setEntityGuid(UUID value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.entity_access.entity_guid</code>.
	 */
	public UUID getEntityGuid() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.entity_access.accessor_guid</code>.
	 */
	public EntityAccessRecord setAccessorGuid(UUID value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.entity_access.accessor_guid</code>.
	 */
	public UUID getAccessorGuid() {
		return (UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.entity_access.access_level</code>.
	 */
	public EntityAccessRecord setAccessLevel(Integer value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.entity_access.access_level</code>.
	 */
	public Integer getAccessLevel() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<UUID, UUID, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<UUID, UUID, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return EntityAccess.ENTITY_ACCESS.ENTITY_GUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field2() {
		return EntityAccess.ENTITY_ACCESS.ACCESSOR_GUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return EntityAccess.ENTITY_ACCESS.ACCESS_LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getEntityGuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value2() {
		return getAccessorGuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getAccessLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntityAccessRecord value1(UUID value) {
		setEntityGuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntityAccessRecord value2(UUID value) {
		setAccessorGuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntityAccessRecord value3(Integer value) {
		setAccessLevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntityAccessRecord values(UUID value1, UUID value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EntityAccessRecord
	 */
	public EntityAccessRecord() {
		super(EntityAccess.ENTITY_ACCESS);
	}

	/**
	 * Create a detached, initialised EntityAccessRecord
	 */
	public EntityAccessRecord(UUID entityGuid, UUID accessorGuid, Integer accessLevel) {
		super(EntityAccess.ENTITY_ACCESS);

		setValue(0, entityGuid);
		setValue(1, accessorGuid);
		setValue(2, accessLevel);
	}
}
