/**
 * This class is generated by jOOQ
 */
package ch.johannes.example.data.schema.tables.records;


import ch.johannes.example.data.schema.tables.GroupMembership;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupMembershipRecord extends UpdatableRecordImpl<GroupMembershipRecord> implements Record3<UUID, UUID, Integer> {

	private static final long serialVersionUID = 1200817754;

	/**
	 * Setter for <code>public.group_membership.group_guid</code>.
	 */
	public GroupMembershipRecord setGroupGuid(UUID value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.group_membership.group_guid</code>.
	 */
	public UUID getGroupGuid() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.group_membership.member_guid</code>.
	 */
	public GroupMembershipRecord setMemberGuid(UUID value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.group_membership.member_guid</code>.
	 */
	public UUID getMemberGuid() {
		return (UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.group_membership.access_level</code>.
	 */
	public GroupMembershipRecord setAccessLevel(Integer value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.group_membership.access_level</code>.
	 */
	public Integer getAccessLevel() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<UUID, UUID> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<UUID, UUID, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<UUID, UUID, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return GroupMembership.GROUP_MEMBERSHIP.GROUP_GUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field2() {
		return GroupMembership.GROUP_MEMBERSHIP.MEMBER_GUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return GroupMembership.GROUP_MEMBERSHIP.ACCESS_LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getGroupGuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value2() {
		return getMemberGuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getAccessLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupMembershipRecord value1(UUID value) {
		setGroupGuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupMembershipRecord value2(UUID value) {
		setMemberGuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupMembershipRecord value3(Integer value) {
		setAccessLevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupMembershipRecord values(UUID value1, UUID value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GroupMembershipRecord
	 */
	public GroupMembershipRecord() {
		super(GroupMembership.GROUP_MEMBERSHIP);
	}

	/**
	 * Create a detached, initialised GroupMembershipRecord
	 */
	public GroupMembershipRecord(UUID groupGuid, UUID memberGuid, Integer accessLevel) {
		super(GroupMembership.GROUP_MEMBERSHIP);

		setValue(0, groupGuid);
		setValue(1, memberGuid);
		setValue(2, accessLevel);
	}
}
