/**
 * This class is generated by jOOQ
 */
package ch.johannes.example.data.schema.tables.records;


import ch.johannes.example.data.schema.tables.GroupAccessView;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupAccessViewRecord extends TableRecordImpl<GroupAccessViewRecord> implements Record3<UUID, UUID, Integer> {

	private static final long serialVersionUID = 881367142;

	/**
	 * Setter for <code>public.group_access_view.member_guid</code>.
	 */
	public GroupAccessViewRecord setMemberGuid(UUID value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.group_access_view.member_guid</code>.
	 */
	public UUID getMemberGuid() {
		return (UUID) getValue(0);
	}

	/**
	 * Setter for <code>public.group_access_view.group_guid</code>.
	 */
	public GroupAccessViewRecord setGroupGuid(UUID value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.group_access_view.group_guid</code>.
	 */
	public UUID getGroupGuid() {
		return (UUID) getValue(1);
	}

	/**
	 * Setter for <code>public.group_access_view.access_level</code>.
	 */
	public GroupAccessViewRecord setAccessLevel(Integer value) {
		setValue(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.group_access_view.access_level</code>.
	 */
	public Integer getAccessLevel() {
		return (Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<UUID, UUID, Integer> fieldsRow() {
		return (Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row3<UUID, UUID, Integer> valuesRow() {
		return (Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field1() {
		return GroupAccessView.GROUP_ACCESS_VIEW.MEMBER_GUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<UUID> field2() {
		return GroupAccessView.GROUP_ACCESS_VIEW.GROUP_GUID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return GroupAccessView.GROUP_ACCESS_VIEW.ACCESS_LEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value1() {
		return getMemberGuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UUID value2() {
		return getGroupGuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getAccessLevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupAccessViewRecord value1(UUID value) {
		setMemberGuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupAccessViewRecord value2(UUID value) {
		setGroupGuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupAccessViewRecord value3(Integer value) {
		setAccessLevel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupAccessViewRecord values(UUID value1, UUID value2, Integer value3) {
		value1(value1);
		value2(value2);
		value3(value3);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GroupAccessViewRecord
	 */
	public GroupAccessViewRecord() {
		super(GroupAccessView.GROUP_ACCESS_VIEW);
	}

	/**
	 * Create a detached, initialised GroupAccessViewRecord
	 */
	public GroupAccessViewRecord(UUID memberGuid, UUID groupGuid, Integer accessLevel) {
		super(GroupAccessView.GROUP_ACCESS_VIEW);

		setValue(0, memberGuid);
		setValue(1, groupGuid);
		setValue(2, accessLevel);
	}
}
