/**
 * This class is generated by jOOQ
 */
package ch.johannes.example.data.schema.tables;


import ch.johannes.example.data.schema.Public;
import ch.johannes.example.data.schema.tables.records.EntityAccessRecord;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityAccess extends TableImpl<EntityAccessRecord> {

	private static final long serialVersionUID = -893654770;

	/**
	 * The reference instance of <code>public.entity_access</code>
	 */
	public static final EntityAccess ENTITY_ACCESS = new EntityAccess();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EntityAccessRecord> getRecordType() {
		return EntityAccessRecord.class;
	}

	/**
	 * The column <code>public.entity_access.entity_guid</code>.
	 */
	public final TableField<EntityAccessRecord, UUID> ENTITY_GUID = createField("entity_guid", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.entity_access.accessor_guid</code>.
	 */
	public final TableField<EntityAccessRecord, UUID> ACCESSOR_GUID = createField("accessor_guid", org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

	/**
	 * The column <code>public.entity_access.access_level</code>.
	 */
	public final TableField<EntityAccessRecord, Integer> ACCESS_LEVEL = createField("access_level", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>public.entity_access</code> table reference
	 */
	public EntityAccess() {
		this("entity_access", null);
	}

	/**
	 * Create an aliased <code>public.entity_access</code> table reference
	 */
	public EntityAccess(String alias) {
		this(alias, ENTITY_ACCESS);
	}

	private EntityAccess(String alias, Table<EntityAccessRecord> aliased) {
		this(alias, aliased, null);
	}

	private EntityAccess(String alias, Table<EntityAccessRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EntityAccess as(String alias) {
		return new EntityAccess(alias, this);
	}

	/**
	 * Rename this table
	 */
	public EntityAccess rename(String name) {
		return new EntityAccess(name, null);
	}
}
