/**
 * This class is generated by jOOQ
 */
package ch.johannes.example.data.schema.tables;


import ch.johannes.example.data.schema.Public;
import ch.johannes.example.data.schema.tables.records.GroupAccessViewRecord;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupAccessView extends TableImpl<GroupAccessViewRecord> {

	private static final long serialVersionUID = 2132721008;

	/**
	 * The reference instance of <code>public.group_access_view</code>
	 */
	public static final GroupAccessView GROUP_ACCESS_VIEW = new GroupAccessView();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<GroupAccessViewRecord> getRecordType() {
		return GroupAccessViewRecord.class;
	}

	/**
	 * The column <code>public.group_access_view.member_guid</code>.
	 */
	public final TableField<GroupAccessViewRecord, UUID> MEMBER_GUID = createField("member_guid", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>public.group_access_view.group_guid</code>.
	 */
	public final TableField<GroupAccessViewRecord, UUID> GROUP_GUID = createField("group_guid", org.jooq.impl.SQLDataType.UUID, this, "");

	/**
	 * The column <code>public.group_access_view.access_level</code>.
	 */
	public final TableField<GroupAccessViewRecord, Integer> ACCESS_LEVEL = createField("access_level", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>public.group_access_view</code> table reference
	 */
	public GroupAccessView() {
		this("group_access_view", null);
	}

	/**
	 * Create an aliased <code>public.group_access_view</code> table reference
	 */
	public GroupAccessView(String alias) {
		this(alias, GROUP_ACCESS_VIEW);
	}

	private GroupAccessView(String alias, Table<GroupAccessViewRecord> aliased) {
		this(alias, aliased, null);
	}

	private GroupAccessView(String alias, Table<GroupAccessViewRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GroupAccessView as(String alias) {
		return new GroupAccessView(alias, this);
	}

	/**
	 * Rename this table
	 */
	public GroupAccessView rename(String name) {
		return new GroupAccessView(name, null);
	}
}
