/**
 * This class is generated by jOOQ
 */
package ch.johannes.example.data.schema.tables;


import ch.johannes.example.data.schema.Public;
import ch.johannes.example.data.schema.tables.records.PersonAndAddressViewRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PersonAndAddressView extends TableImpl<PersonAndAddressViewRecord> {

	private static final long serialVersionUID = 508741471;

	/**
	 * The reference instance of <code>public.person_and_address_view</code>
	 */
	public static final PersonAndAddressView PERSON_AND_ADDRESS_VIEW = new PersonAndAddressView();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<PersonAndAddressViewRecord> getRecordType() {
		return PersonAndAddressViewRecord.class;
	}

	/**
	 * The column <code>public.person_and_address_view.person_id</code>.
	 */
	public final TableField<PersonAndAddressViewRecord, Integer> PERSON_ID = createField("person_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.person_and_address_view.firstname</code>.
	 */
	public final TableField<PersonAndAddressViewRecord, String> FIRSTNAME = createField("firstname", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.person_and_address_view.lastname</code>.
	 */
	public final TableField<PersonAndAddressViewRecord, String> LASTNAME = createField("lastname", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.person_and_address_view.address_id</code>.
	 */
	public final TableField<PersonAndAddressViewRecord, Integer> ADDRESS_ID = createField("address_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.person_and_address_view.street</code>.
	 */
	public final TableField<PersonAndAddressViewRecord, String> STREET = createField("street", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * The column <code>public.person_and_address_view.zip_code</code>.
	 */
	public final TableField<PersonAndAddressViewRecord, Integer> ZIP_CODE = createField("zip_code", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>public.person_and_address_view.city</code>.
	 */
	public final TableField<PersonAndAddressViewRecord, String> CITY = createField("city", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

	/**
	 * Create a <code>public.person_and_address_view</code> table reference
	 */
	public PersonAndAddressView() {
		this("person_and_address_view", null);
	}

	/**
	 * Create an aliased <code>public.person_and_address_view</code> table reference
	 */
	public PersonAndAddressView(String alias) {
		this(alias, PERSON_AND_ADDRESS_VIEW);
	}

	private PersonAndAddressView(String alias, Table<PersonAndAddressViewRecord> aliased) {
		this(alias, aliased, null);
	}

	private PersonAndAddressView(String alias, Table<PersonAndAddressViewRecord> aliased, Field<?>[] parameters) {
		super(alias, Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PersonAndAddressView as(String alias) {
		return new PersonAndAddressView(alias, this);
	}

	/**
	 * Rename this table
	 */
	public PersonAndAddressView rename(String name) {
		return new PersonAndAddressView(name, null);
	}
}
