/**
 * This class is generated by jOOQ
 */
package ch.johannes.example.data.schema.enums;


import ch.johannes.example.data.schema.Public;

import javax.annotation.Generated;

import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public enum GenderTypeEnum implements EnumType {

	FEMALE("FEMALE"),

	MALE("MALE"),

	UNDEFINED("UNDEFINED");

	private final String literal;

	private GenderTypeEnum(String literal) {
		this.literal = literal;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Schema getSchema() {
		return Public.PUBLIC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getName() {
		return "gender_type_enum";
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String getLiteral() {
		return literal;
	}
}
