/**
 * This class is generated by jOOQ
 */
package ch.johannes.example.data.schema;


import ch.johannes.example.data.schema.tables.Address;
import ch.johannes.example.data.schema.tables.EntityAccess;
import ch.johannes.example.data.schema.tables.EntityAccessView;
import ch.johannes.example.data.schema.tables.GroupAccessView;
import ch.johannes.example.data.schema.tables.GroupMembership;
import ch.johannes.example.data.schema.tables.Person;
import ch.johannes.example.data.schema.tables.PersonAndAddressView;
import ch.johannes.example.data.schema.tables.SchemaVersion;
import ch.johannes.example.data.schema.tables.UserMapping;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.3"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.address
	 */
	public static final Address ADDRESS = ch.johannes.example.data.schema.tables.Address.ADDRESS;

	/**
	 * The table public.entity_access
	 */
	public static final EntityAccess ENTITY_ACCESS = ch.johannes.example.data.schema.tables.EntityAccess.ENTITY_ACCESS;

	/**
	 * The table public.entity_access_view
	 */
	public static final EntityAccessView ENTITY_ACCESS_VIEW = ch.johannes.example.data.schema.tables.EntityAccessView.ENTITY_ACCESS_VIEW;

	/**
	 * The table public.group_access_view
	 */
	public static final GroupAccessView GROUP_ACCESS_VIEW = ch.johannes.example.data.schema.tables.GroupAccessView.GROUP_ACCESS_VIEW;

	/**
	 * The table public.group_membership
	 */
	public static final GroupMembership GROUP_MEMBERSHIP = ch.johannes.example.data.schema.tables.GroupMembership.GROUP_MEMBERSHIP;

	/**
	 * The table public.person
	 */
	public static final Person PERSON = ch.johannes.example.data.schema.tables.Person.PERSON;

	/**
	 * The table public.person_and_address_view
	 */
	public static final PersonAndAddressView PERSON_AND_ADDRESS_VIEW = ch.johannes.example.data.schema.tables.PersonAndAddressView.PERSON_AND_ADDRESS_VIEW;

	/**
	 * The table public.schema_version
	 */
	public static final SchemaVersion SCHEMA_VERSION = ch.johannes.example.data.schema.tables.SchemaVersion.SCHEMA_VERSION;

	/**
	 * The table public.user_mapping
	 */
	public static final UserMapping USER_MAPPING = ch.johannes.example.data.schema.tables.UserMapping.USER_MAPPING;
}
